### ISSUE TITLE
ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).

### ISSUE THREAD

**Issue by tobiashochguertel** [standardnotes/server#1003]
The docker container `localstack_self_hosted` (latest, pulled today) throws countless errors (all the same):

```
localstack_self_hosted | 2023-12-19T08:52:03.668 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.671 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.736 ERROR --- [   asgi_gw_5] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.744 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.748 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.752 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.796 ERROR --- [   asgi_gw_5] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.799 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.811 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.812 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.856 ERROR --- [   asgi_gw_3] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.859 ERROR --- [   asgi_gw_5] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.863 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.870 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.916 ERROR --- [   asgi_gw_4] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.917 ERROR --- [   asgi_gw_3] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.924 ERROR --- [   asgi_gw_5] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.926 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
localstack_self_hosted | 2023-12-19T08:52:03.991 ERROR --- [   asgi_gw_3] l.aws.handlers.logging     : exception during call chain: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
```

My docker compose file:

```
---
version: "3.8"

networks:
  standardnotes_self_hosted:
    name: standardnotes_self_hosted
  proxy:
    external: true
  intranet:
    external: true

services:
  webclient:
    image: standardnotes/web:stable
    env_file: webclient.env
    # ports:
    #   - 3001:3001
    depends_on:
      - server
    networks:
      - standardnotes_self_hosted
      - proxy
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https://standardnotes.vps4.hochguertel.work
      - "traefik.http.routers.standardnotes.entrypoints=http"
      - "traefik.http.routers.standardnotes.rule=Host(`standardnotes.vps4.hochguertel.work`)"
      - "traefik.http.routers.standardnotes.service=standardnotes"
      - "traefik.http.services.standardnotes.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.standardnotes-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.standardnotes.middlewares=standardnotes-https-redirect"
      - "traefik.http.routers.standardnotes-secure.entrypoints=https"
      - "traefik.http.routers.standardnotes-secure.rule=Host(`standardnotes.vps4.hochguertel.work`)"
      - "traefik.http.routers.standardnotes-secure.service=standardnotes"
      - "traefik.http.routers.standardnotes-secure.tls=true"
      - "traefik.http.routers.standardnotes-secure.tls.certresolver=http"
  server:
    image: standardnotes/server
    env_file: .env
    container_name: server_self_hosted
    # ports:
    # - 3000:3000
    # - 3125:3104
    depends_on:
      - db
    volumes:
      - ./logs:/var/lib/server/logs
      - ./uploads:/opt/server/packages/files/dist/uploads:Z
    networks:
      - standardnotes_self_hosted
      - proxy
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https://api.standardnotes.vps4.hochguertel.work
      - "traefik.http.routers.api-standardnotes.entrypoints=http"
      - "traefik.http.routers.api-standardnotes.rule=Host(`api.standardnotes.vps4.hochguertel.work`)"
      - "traefik.http.routers.api-standardnotes.service=api-standardnotes"
      - "traefik.http.services.api-standardnotes.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.api-standardnotes-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.api-standardnotes.middlewares=standardnotes-https-redirect"
      - "traefik.http.routers.api-standardnotes-secure.entrypoints=https"
      - "traefik.http.routers.api-standardnotes-secure.rule=Host(`api.standardnotes.vps4.hochguertel.work`)"
      - "traefik.http.routers.api-standardnotes-secure.service=api-standardnotes"
      - "traefik.http.routers.api-standardnotes-secure.tls=true"
      - "traefik.http.routers.api-standardnotes-secure.tls.certresolver=http"
      # https://files.standardnotes.vps4.hochguertel.work
      - "traefik.http.routers.files-standardnotes.entrypoints=http"
      - "traefik.http.routers.files-standardnotes.rule=Host(`files.standardnotes.vps4.hochguertel.work`)"
      - "traefik.http.routers.files-standardnotes.service=files-standardnotes"
      - "traefik.http.services.files-standardnotes.loadbalancer.server.port=3104"
      - "traefik.http.middlewares.files-standardnotes-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.files-standardnotes.middlewares=files-standardnotes-https-redirect"
      - "traefik.http.routers.files-standardnotes-secure.entrypoints=https"
      - "traefik.http.routers.files-standardnotes-secure.rule=Host(`files.standardnotes.vps4.hochguertel.work`)"
      - "traefik.http.routers.files-standardnotes-secure.service=files-standardnotes"
      - "traefik.http.routers.files-standardnotes-secure.tls=true"
      - "traefik.http.routers.files-standardnotes-secure.tls.certresolver=http"

  localstack:
    image: localstack/localstack:1.3
    container_name: localstack_self_hosted
    # expose:
    #   - 4566
    depends_on:
      - server
    restart: unless-stopped
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=warn
    volumes:
      - ./localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
    networks:
      - standardnotes_self_hosted

  db:
    image: mysql:8
    container_name: db_self_hosted
    environment:
      - MYSQL_DATABASE=***
      - MYSQL_USER=***
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_PASSWORD=***
    # expose:
    #   - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d
    networks:
      - standardnotes_self_hosted
      - intranet

  cache:
    image: redis:6.0-alpine
    container_name: cache_self_hosted
    # expose:
    #   - 6379
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./data/redis/:/data
    networks:
      - standardnotes_self_hosted
```

How can I solve this?
