### ISSUE TITLE
DB, API-GATEWAY & AUTH waiting to start

### ISSUE THREAD

**Issue by ZuluPilgrim** [standardnotes/server#1052]
Can't work out what I might have done wrong.

I have checked my ports and db passwords

```
db:3309 is unavailable yet - waiting for it to start

==> logs/api-gateway.log <==
localhost:3103 is unavailable yet - waiting for it to start

==> logs/auth.log <==
localhost:3101 is unavailable yet - waiting for it to start
```

The logs report a bad DB address
```
==> logs/api-gateway.err <==

==> logs/auth-worker.err <==

==> logs/auth.err <==

==> logs/files-worker.err <==

==> logs/files.err <==
==> logs/revisions-worker.err <==

==> logs/revisions.err <==

==> logs/syncing-server-worker.err <==

==> logs/syncing-server.err <==
nc: bad address 'db'

```

**Comment by ZuluPilgrim** [comment]
.env file
```
######
# DB #
######

DB_HOST=db
DB_PORT=3309
DB_USERNAME=std_notes_user
DB_PASSWORD=pwddb
DB_DATABASE=standard_notes_db
DB_TYPE=mysql

#########
# CACHE #
#########

REDIS_PORT=6379
REDIS_HOST=cache
CACHE_TYPE=redis

########
# KEYS #
########

AUTH_JWT_SECRET=pwd1
AUTH_SERVER_ENCRYPTION_SERVER_KEY=pw2
VALET_TOKEN_SECRET=pw3

# PUBLIC_FILES_SERVER_URL=

```

docker-compose

```
services:
  server:
    image: standardnotes/server
    env_file: .env
    container_name: server_self_hosted
    restart: unless-stopped
    ports:
      - 3005:3000
      - 3125:3104
    volumes:
      - ./logs:/var/lib/server/logs
      - ./uploads:/opt/server/packages/files/dist/uploads
    networks:
      - standardnotes_self_hosted

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack_self_hosted
      - 4566
    restart: unless-stopped
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=warn
    volumes:
      - ./localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
    networks:
      - standardnotes_self_hosted

  db:
    image: mysql:8
    container_name: db_self_hosted
    environment:
      - MYSQL_DATABASE=standard_notes_db
      - MYSQL_USER=std_notes_user
      - MYSQL_ROOT_PASSWORD=pwddb
      - MYSQL_PASSWORD=pwddb
    expose:
      - 3309
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d
    networks:
      - standardnotes_self_hosted

  cache:
    image: redis:6.0-alpine
    container_name: cache_self_hosted
    volumes:
      - ./data/redis/:/data
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - standardnotes_self_hosted

networks:
  standardnotes_self_hosted:
    name: standardnotes_self_hosted


```
