### ISSUE TITLE
App and web keep asking me for login (self-hosted)

### ISSUE THREAD

**Issue by lfloresbatista** [standardnotes/server#1060]
I'm testing standard notes server with all the configuration, everything going well, but when i login to sync with my server the app (web and desktop) still asking me for login constantly, im sharing you the docker-compose file, and the logs of the different containers:

compose file:
```
version: '3.7'

services:
  server:
    image: standardnotes/server
    container_name: sersnotes_server
#    hostname: snotes
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3125:3104
    volumes:
      - logs:/var/lib/server/logs
      - uploads:/opt/server/packages/files/dist/uploads
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: snotes_usr
      DB_PASSWORD: *****
      DB_DATABASE: snotesdb
      DB_TYPE: mysql
      #run for each env openssl rand -hex 32
      AUTH_JWT_SECRET: 1c5c1defbd68c6167a1656a1d8bcef641dcfab2df6ac7e80adba2feb580537b8
      AUTH_SERVER_ENCRYPTION_SERVER_KEY: 405b060dcf42674d36eec5bceeed240638fc5bdbc5539c5237a34291f1fd92e0
      VALET_TOKEN_SECRET: b77f7d78317d23c2002b18dfe0a8e35d726bac2125b567ea2bd87af535386d90
      REDIS_PORT: 6379
      REDIS_HOST: cache
      CACHE_TYPE: redis
      PUBLIC_FILES_SERVER_URL: http://localhost:3125
    networks:
      - okami-bridge
    depends_on:
      - cache
      
  web:
    image: standardnotes/web
    container_name: notes
    restart: unless-stopped
    ports:
      - 88:80
    depends_on:
      - server
      - cache
    networks:
      - okami-bridge

  localstack:
    image: localstack/localstack:3.5.0
    container_name: localstack_self_hosted
    expose:
      - 4566
    restart: unless-stopped
    environment:
      SERVICES: sns,sqs
      HOSTNAME_EXTERNAL: localstack
      LS_LOG: warn
    volumes:
      - /var/lib/docker/volumes/files/scripts/localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
    networks:
      - okami-bridge

  cache:
    image: redis:6.0-alpine
    container_name: snotes_cache
    volumes:
      - redis:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: cache
      CACHE_TYPE: redis
    networks:
      - okami-bridge

networks:
  okami-bridge:
    external: true
    
volumes:
  logs:
  uploads:
  redis:

```
i'm using a mysql container thar i already use for my homelabs, this container is in the same network as the snote server, im sharing the ping response:
![image](https://github.com/user-attachments/assets/80e258de-4b17-42b3-9e82-9bdf7eece8e8)

These are the logs for the entire container:
![image](https://github.com/user-attachments/assets/c79ee904-c01c-4e98-9ac5-66fc05c663cc)

Sync web screenshot:

![image](https://github.com/user-attachments/assets/5cf37ec6-6672-4579-94b6-bbae5d77a892)

if someone can give some light about, I'll appreciate it

**Comment by Wadera** [comment]
It seems like current server version is buggy.

Try to specify older version: 

```
services:
  server:
    image: standardnotes/server:5c02435ee478b893747d3f9e41062aae12d7ff10
    env_file: .env
    container_name: server_self_hosted
    restart: unless-stopped
    links:
(...)
```
